# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14583486a8ceb3b7fa1ae57e34b68f2b140b225a06e3a783e6d015a2acc79f61012b2446ca1e6705e10a94de88425556931a71f7e4d3bf2965fd80a21928b382

test:
  secret_key_base: 3a10ab1306420c529f4ae412f8028c838f48d83f9fba2b99086b09ec5ebd0aa43014bc9973650823d9c18b50f735d06e133ba1d52822497712a44733e70c6f48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
